apiVersion: apps/v1
kind: Deployment
metadata:
  name: anasvip-deployment
  labels:
    app: anasvip
spec:
  replicas: 3
  selector:
    matchLabels:
      app: anasvip
  template:
    metadata:
      labels:
        app: anasvip
    spec:
      containers:
      - name: anasvip
        image: anasaljboor/anas:v2
        ports:
        - containerPort: 80
